version: '2'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_URI="mongodb://mongo:27017/drive2park"
    ports:
      - "8080:3001"
    depends_on:
      - mongo
  frontend:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - backend
      - mongo