version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./server/
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app
    depends_on:
      - backend